BlogSite/BlogSite.Web/Models/tourViewModel/TourViewModel.cs
using Autofac;
using Blogsite.Infrastructure.Entities;
using Blogsite.Infrastructure.Services;
using BlogSite.Web.Areas.Admin.Models;
using DevSkill.Data;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BlogSite.Web.Models.tourViewModel
{
    public class TourViewModel:AdminBaseModel
    {
        protected ITourServices _tourServices;

        public int TourId { get; set; }
        public string? TourName { get; set; }
        public string? TourUrl { get; set; }
        public string? Destination { get; set; }
        public int MaxiMumPeople { get; set; }
        public int MiniMumPeople { get; set; }
        public string? MapUrl { get; set; }
        public string? Requirements { get; set; }
        public string? CancellationTerm { get; set; }
        public double Price { get; set; }
        public int SpotsAvailable { get; set; }
        public  IList<Tour> TourList { set; get; }
        public int Count {  get; set; } 
        public TourViewModel(IHttpContextAccessor httpContext,ITourServices tourServices):base(httpContext)
        {
            _tourServices = tourServices;
        }
        public TourViewModel() {
        }

        public override void ResolveDependency(ILifetimeScope lifetimeScope)
        {
            _lifetimeScope = lifetimeScope;
            _tourServices = _lifetimeScope.Resolve<ITourServices>();
            base.ResolveDependency(lifetimeScope);
        }
       
        public IList<Tour> PopularTourDestination()
        {
            var data = _tourServices.ListOfPopularDestination();
            TourList = new List<Tour>();

            if (data != null)
            {
                foreach (var item in data)
                {
                    TourList.Add(new Tour
                    {
                        Id = item.Id,
                        TourUrl = item.TourUrl,
                        TourName = item.TourName,
                        Destination = item.Destination,
                    });

                }
            }
            return TourList;
        }
        public IList<Tour> ListofTour(string destination)
        {
            var entity = _tourServices.ListOfTour(destination);
            Count = entity.Count;
            TourList=new List<Tour>();
            foreach (var item in entity)
            {
                TourList.Add(new Tour
                {
                    Id = item.Id,
                    TourUrl=item.TourUrl,
                    TourName=item.TourName,
                    Destination=item.Destination,
                    MaxiMumPeople=item.MaxiMumPeople,   
                    MiniMumPeople=item.MiniMumPeople,   
                    Requirements=item.Requirements, 
                    CancellationTerm=item.CancellationTerm, 
                    Price=item.Price,
                    SpotsAvailable=item.SpotsAvailable, 
                });

            }
            return TourList;    
        }
        public IList<Tour> ListOfTours()
        {
            var entity = _tourServices.ListOfPopularTours();
            TourList = new List<Tour>();
            foreach(var tour in entity)
            {
                TourList.Add(new Tour
                {
                    Id = tour.Id,   
                    TourUrl = tour.TourUrl,
                    Destination = tour.Destination,
                    TourName = tour.TourName,
                   Price = tour.Price,
                });
              
            }  
            return TourList;
        }
        public IList<SelectListItem> TourDropdownList()
        {
            var hotel = new List<SelectListItem>();
            foreach (var item in _tourServices.GetAllTourForDropDown())
            {
                var addItem = new SelectListItem
                {
                    Text = item.Destination,   // Display Location Name
                    Value = item.Destination   // Ensure Value is also Location Name
                };
                hotel.Add(addItem);
            }
            return hotel;
        }



    }
}

BlogSite/BlogSite.Web/Areas/Admin/Controllers/TourController.cs
using Autofac;
using Autofac.Core.Lifetime;
using Blogsite.Infrastructure;
using Blogsite.Infrastructure.Entities;
using BlogSite.Web.Areas.Admin.Models;
using BlogSite.Web.Areas.Admin.Models.TourModelFolder;
using BlogSite.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System.CodeDom;
using System.Security.Cryptography.X509Certificates;

namespace BlogSite.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "User, Admin")]

    public class TourController : Controller
    {
        protected readonly ILifetimeScope _scope;
        IFileHelper _fileHelper;
        protected readonly ILogger<TourController> _logger;  
        public TourController(ILifetimeScope scope,IFileHelper fileHelper,ILogger<TourController> logger)
        {
                _fileHelper = fileHelper;
                _scope = scope; 
                 _logger = logger;   
        }
        public IActionResult Index()
        {
            var model = _scope.Resolve<TourModel>();

           return View(model);
        }
        public IActionResult GetTour()
        {
            var tableModel = new DataTablesAjaxRequestModel(Request);
            var model = _scope.Resolve<TourModel>();
            var data = model.GetTour(tableModel);
            return Json(data);
        }
        public async Task<IActionResult> Add()
        {
            var model = _scope.Resolve<CreateTour>();
            return View(model);
        }
        [HttpPost]
        public IActionResult Add(CreateTour tour)
        {
            tour.ResolveDependency(_scope);
            if (ModelState.IsValid)
            {
                try
                {
                    tour.TourUrl = _fileHelper.UploadFile(tour.CoverPhotoUrl);
                    if (tour.UrlList == null)
                    {
                        tour.UrlList = new List<string>();
                    }
                    if (tour.ListofImages != null)
                    {
                        foreach (var item in tour.ListofImages)
                        {
                            tour.UrlList.Add(_fileHelper.UploadFile(item));
                        }
                    }
                    tour.AddTour();
                    tour.Response = new ResponseModel("Added successfully", ResponseType.Success);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    _logger.LogError($"{ex.Message}");
                    tour.Response = new ResponseModel("Fail", ResponseType.Failure);
                }
            }
            return View(tour);
        }
        
       public IActionResult GetById(int id)
        {
            var model=_scope.Resolve<TourModel>(); 
            model.getByid(17);
            return View();
        }
        public IActionResult GetByDestination(string destination)
        {
            var model = _scope.Resolve<TourModel>();
            model.getByDestination("Sundarban");
            return View();
        }
        public IActionResult EditTour(int id)
        {
            var model = _scope.Resolve<EditTourModel>();
            model.Load(id);
            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult EditTour(EditTourModel model)
        {
            model.ResolveDependency(_scope);

            if (ModelState.IsValid)
            {
                try
                {
                    if (model.CoverPhotoUrl != null)
                    {
                        _fileHelper.DeleteFile(model.TourUrl);
                        model.TourUrl = _fileHelper.UploadFile(model.CoverPhotoUrl);
                    }
                    model.Edit();
                    model.Response = new ResponseModel("Edited successfully", ResponseType.Success);
                    return RedirectToAction("Index");
                }
                //catch (DuplicationException ex)
                //{
                //    //model.Response = new ResponseModel(ex.Message, ResponseType.Failure);
                //}
                catch (Exception ex)
                {
                    _logger.LogError($"{ex.Message}");

                   model.Response = new ResponseModel("edited fail", ResponseType.Failure);
                }
            }
            return View(model);
        }
        [HttpPost,ValidateAntiForgeryToken]
        public  ActionResult Delete(int id) 
        {
            var dataDelete = _scope.Resolve<CreateTour>();

            try
            {
                dataDelete.RemoveTour(id);
                dataDelete.Response = new ResponseModel("Deleted", ResponseType.Success);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                _logger.LogError($"{ex.Message}");
                dataDelete.Response = new ResponseModel("Failed to delete", ResponseType.Failure);
            }
            return RedirectToAction(nameof(Index));
        }

    }
}

BlogSite/BlogSite.Web/Areas/Admin/Views/Tour/Add.cshtml
@model CreateTour

@{
    ViewData["Title"] = "Create New Tour";
}

<div class="container p-5 my-5 border">
    <form asp-action="Add" method="post" enctype="multipart/form-data">
        <div class="form-group">
            <label asp-for="TourName" class="control-label"></label>
            <input asp-for="TourName" class="form-control" />
            <span asp-validation-for="TourName" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="CoverPhotoUrl" class="control-label">Cover Photo</label>
            <input asp-for="CoverPhotoUrl" type="file" class="form-control" />
            <span asp-validation-for="CoverPhotoUrl" class="text-danger"></span>
        </div>
        <div class="form-group ">
            <label asp-for="TourDetailsId" class="control-label">Type</label>
                <select asp-for="TourDetailsId" asp-items="@Model.ListOfTourDetails()" class="form-control">
                    <option>Please Select One</option>
                </select>
                <span asp-validation-for="TourDetailsId" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Destination" class="control-label">Destination</label>
            <input asp-for="Destination" class="form-control" />
            <span asp-validation-for="Destination" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="MaxiMumPeople" class="control-label">Maximum People</label>
            <input asp-for="MaxiMumPeople" class="form-control" />
            <span asp-validation-for="MaxiMumPeople" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="MiniMumPeople" class="control-label">Minimum People</label>
            <input asp-for="MiniMumPeople" class="form-control" />
            <span asp-validation-for="MiniMumPeople" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="MapUrl" class="control-label">Map URL</label>
            <input asp-for="MapUrl" class="form-control" />
            <span asp-validation-for="MapUrl" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Requirements" class="control-label">Requirements</label>
            <input asp-for="Requirements" class="form-control" />
            <span asp-validation-for="Requirements" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="CancellationTerm" class="control-label">Cancellation Terms</label>
            <textarea asp-for="CancellationTerm" class="form-control"></textarea>
            <span asp-validation-for="CancellationTerm" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Price" class="control-label">Price</label>
            <input asp-for="Price" class="form-control" />
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="SpotsAvailable" class="control-label">Spots Available</label>
            <input asp-for="SpotsAvailable" class="form-control" />
            <span asp-validation-for="SpotsAvailable" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="ListofImages" class="control-label">Tour Images</label>
            <input asp-for="ListofImages" type="file" multiple class="form-control" />
            <span asp-validation-for="ListofImages" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>
    </form>
</div>


@section PageScript
{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

BlogSite/BlogSite.Web/Areas/Admin/Views/Tour/EditTour.cshtml
@model  EditTourModel

@{
    ViewData["Title"] = "EditTour";
}

<form asp-area="Admin" asp-controller="Tour" asp-action="EditTour" asp-antiforgery="true"
      method="post" enctype="multipart/form-data">
    <div class="row p-3 border">
        <div class="col-12 border-bottom ">
            <h2 class="text-warning">@Model.TourName</h2>
        </div>
        <div class="col-8 pt-4">
            <input type="hidden" asp-for="TourId" />

            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="TourName"></label>
                </div>
                <div class="col-8">
                    <input asp-for="TourName" class="form-control" />
                    <span asp-validation-for="TourName" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Destination"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Destination" class="form-control" />
                    <span asp-validation-for="Destination" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="MaxiMumPeople"></label>
                </div>
                <div class="col-8">
                    <input asp-for="MaxiMumPeople" class="form-control" />
                    <span asp-validation-for="MaxiMumPeople" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="MiniMumPeople"></label>
                </div>
                <div class="col-8">
                    <textarea asp-for="MiniMumPeople" class="form-control"></textarea>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Requirements"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Requirements" class="form-control" />
                    <span asp-validation-for="Requirements" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="CancellationTerm"></label>
                </div>
                <div class="col-8">
                    <input asp-for="CancellationTerm" class="form-control" />
                    <span asp-validation-for="CancellationTerm" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Price"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="SpotsAvailable"></label>
                </div>
                <div class="col-8">
                    <input asp-for="SpotsAvailable" class="form-control" />
                    <span asp-validation-for="SpotsAvailable" class="text-danger"></span>
                </div>
            </div>
            
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="CoverPhotoUrl" class="control-label">Form File</label>
                </div>
                <div class="col-8">

                    <input type="file" asp-for="CoverPhotoUrl" class="form-control" style="border:none;padding: .375rem 0;" />
                    <span asp-validation-for="CoverPhotoUrl" class="text-danger"></span>
                    <br />

                </div>
            </div>

            <div class="form-group row">
                <div class="col-4">

                </div>
                <div class="col-8">
                    <input type="submit" value="Save" class="btn btn-primary" />&nbsp;
                    <a asp-action="Index" asp-controller="Tour" class="btn btn-warning">Cancel</a>
                </div>
            </div>
        </div>
        @if (Model != null && !string.IsNullOrEmpty(Model.TourUrl))
        {

            <input type="hidden" asp-for="TourUrl" />
            <img id="itemImage" src="@Model.TourUrl" width="25%" height="30%" style="border-radius:5px; border:1px solid #bbb9b9 " />

        }

    </div>
</form>

@section PageScript
{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BlogSite/BlogSite.Web/Areas/Admin/Views/Tour/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

@section PageStyle
{
    <link rel="stylesheet" href="/Admin/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <table id="tour" class="table table table-striped table-bordered">
                    <thead class="thead-dark">
                        <tr class="table-info">
                            <th>Tour</th>
                            <th>Photo</th>
                            <th>Destination</th>
                            <th>Requirements</th>
                            <th>Cancellation</th>
                            <th>Price</th>
                            <th>Seat available</th>
                            <th>Action</th>
                        </tr>
                    </thead>

                    <tfoot>
                        <tr class="table-info">
                            <th>Tour</th>
                            <th>Photo</th>
                            <th>Destination</th>
                            <th>Requirements</th>
                            <th>Cancellation</th>
                            <th>Price</th>
                            <th>Seat available</th>
                            <th>Action</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
    <!-- /.col -->
</div>
<!-- /.row -->

<div class="modal fade" id="modal-default">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Delete</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure, you want to delete?</p>
                <form id="deleteForm" action="/admin/Tour/Delete" method="post">
                    @Html.AntiForgeryToken()
                    <input type="hidden" id="deleteId" value="" name="id" />
                </form>
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" id="deleteButton" class="btn btn-danger">Yes, Delete!</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->
@section PageScript
{
    <script src="/Admin/plugins/datatables/jquery.dataTables.js"></script>
    <script src="/Admin/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>

    <script src="~/js/tourjs.js"></script>

}